In [ ]:
SECTION 1: Theoretical Questions

Q1. What is NumPy, and why is it widely used in Python?
NumPy (Numerical Python) is a fundamental open-source library for scientific computing in Python. It was created by Travis Oliphant in 2005 and provides support for large, multi-dimensional arrays and matrices, along with a rich collection of high-level mathematical functions to operate on these arrays.
Why NumPy is widely used:
•	Performance: NumPy operations are implemented in C, making them orders of magnitude faster than equivalent pure Python code.
•	Memory Efficiency: NumPy arrays store data in contiguous memory blocks, unlike Python lists which store pointers to objects.
•	Broadcasting: Allows arithmetic operations on arrays of different shapes without explicit loops.
•	Foundation: NumPy is the base for almost all data science libraries in Python — Pandas, SciPy, Scikit-learn, TensorFlow all use NumPy arrays internally.
•	Rich Mathematical API: Linear algebra, Fourier transforms, random number generation, statistics — all built-in.
Benchmark comparison: A simple element-wise multiplication on 1 million elements is ~100x faster in NumPy than with Python lists.

Q2. How does broadcasting work in NumPy?
Broadcasting is NumPy's mechanism for performing arithmetic operations on arrays of different shapes. Instead of requiring arrays to have the same shape, NumPy automatically 'stretches' the smaller array across the larger one — without making actual copies of data in memory.
Broadcasting Rules:
•	Rule 1: If arrays have different numbers of dimensions, the shape of the smaller-dimension array is padded with 1s on the left.
•	Rule 2: Arrays with size 1 along a dimension act as if they had the size of the largest array along that dimension.
•	Rule 3: Arrays must be compatible in all dimensions (same size, or one of them is 1).
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = np.array([10, 20, 30])             # shape (3,) -> broadcast to (2,3)
print(a + b)
# Output: [[11, 22, 33],
#          [14, 25, 36]]
In this example, b (shape 3) is broadcast across both rows of a (shape 2x3). This eliminates the need for explicit Python loops, making code cleaner and faster.

Q3. What is a Pandas DataFrame?
A Pandas DataFrame is a two-dimensional, size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). It can be thought of as a spreadsheet or SQL table in Python, where each column can have a different data type (integer, float, string, boolean, etc.).
Key Characteristics:
•	Labeled Axes: Both rows (index) and columns have labels, making data access intuitive.
•	Heterogeneous Data: Different columns can store different data types.
•	Size-Mutable: Columns and rows can be added, removed, or modified.
•	Powerful Operations: Supports groupby, merge, pivot, reshape, and time series operations.
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age':  [25, 30, 28],
        'Score': [92.5, 85.0, 78.3]}
df = pd.DataFrame(data)
print(df)
Output:      Name  Age  Score
0   Alice   25   92.5
1     Bob   30   85.0
2  Charlie   28   78.3

Q4. Explain the use of the groupby() method in Pandas.
The groupby() method in Pandas is used to split a DataFrame into groups based on one or more columns, apply an aggregation function to each group independently, and combine the results back into a DataFrame. This follows the Split-Apply-Combine paradigm.
Common Aggregation Functions:
Function	Description
sum()	Total of each group
mean()	Average of each group
count()	Number of entries per group
min() / max()	Minimum / Maximum value per group
std()	Standard deviation per group
agg()	Apply multiple functions at once

import pandas as pd
df = pd.DataFrame({
    'Department': ['HR','IT','IT','HR','Finance','Finance'],
    'Salary': [50000, 80000, 90000, 55000, 70000, 75000]
})
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)
Output: Department
Finance    72500.0
HR         52500.0
IT         85000.0

Q5. Why is Seaborn preferred for statistical visualizations?
Seaborn is preferred for statistical visualizations because it is built specifically for that purpose, offering high-level abstractions over Matplotlib that make it very easy to create complex statistical plots with minimal code. Here are the key reasons:
•	Built-in Statistical Estimation: Seaborn automatically computes and displays confidence intervals, regression lines, and distribution estimates.
•	Beautiful Default Aesthetics: Seaborn's default color palettes and styles look far more polished than Matplotlib's defaults.
•	Native DataFrame Support: Seaborn functions accept Pandas DataFrames directly and understand column names as labels.
•	Rich Plot Types: Violin plots, pair plots, heat maps, regression plots, categorical plots — all with a single function call.
•	FacetGrid: Easily create multi-panel conditional plots that show data subsets.
Example: Creating a regression plot with confidence interval in just one line: sns.regplot(x='age', y='salary', data=df)

Q6. What are the differences between NumPy arrays and Python lists?
Feature	NumPy Array	Python List
Data Types	Homogeneous (all same type)	Heterogeneous (mixed types allowed)
Memory	Contiguous block, compact	Array of pointers, more overhead
Speed	Very fast (C-based operations)	Slower (interpreted Python)
Operations	Element-wise arithmetic built-in	Requires loops or list comprehensions
Dimensions	Multi-dimensional (ndarray)	Nested lists (awkward)
Broadcasting	Supported natively	Not supported
Size	Fixed after creation	Dynamic (append/remove)
Syntax	np.array([1,2,3])	[1, 2, 3]

import numpy as np
# Python list: element-wise multiply requires loop
lst = [1, 2, 3]
print([x * 2 for x in lst])  # [2, 4, 6]

# NumPy: direct operation
arr = np.array([1, 2, 3])
print(arr * 2)  # [2 4 6]

Q7. What is a heatmap, and when should it be used?
A heatmap is a data visualization technique that uses color intensity to represent values in a matrix. Each cell of the matrix is colored according to its value, allowing patterns, clusters, and relationships to be identified visually at a glance.
When to Use a Heatmap:
•	Correlation Analysis: Visualizing the correlation matrix of a dataset to identify highly correlated features.
•	Confusion Matrix: Displaying model prediction accuracy across multiple classes in machine learning.
•	Gene Expression Data: Showing expression levels across genes and samples in bioinformatics.
•	Website Analytics: Showing which areas of a webpage receive the most user interaction.
•	Time-Series Patterns: Showing patterns across hours of the day and days of the week.
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
df = sns.load_dataset('iris')
corr = df.drop('species', axis=1).corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Feature Correlation Heatmap')
plt.show()

Q8. What does the term 'vectorized operation' mean in NumPy?
A vectorized operation is an operation that is applied element-wise to an entire array at once, without the need for explicit Python loops. In NumPy, these operations are implemented in compiled C code, which is dramatically faster than the Python interpreter executing a loop.
The concept is called 'vectorization' because it leverages SIMD (Single Instruction, Multiple Data) CPU instructions that can process multiple data elements simultaneously.
import numpy as np
import time

arr = np.arange(1_000_000)

# Python loop (slow)
start = time.time()
result = [x ** 2 for x in arr]
print(f'Loop time: {time.time() - start:.4f}s')

# NumPy vectorized (fast)
start = time.time()
result = arr ** 2
print(f'NumPy time: {time.time() - start:.4f}s')
Sample Output: Loop time: 0.2341s
NumPy time: 0.0021s  (~111x faster)

Q9. How does Matplotlib differ from Plotly?
Feature	Matplotlib	Plotly
Interactivity	Static plots (non-interactive by default)	Fully interactive (zoom, hover, pan)
Output	PNG, PDF, SVG files	HTML, web dashboards
Ease of Use	More verbose, detailed control	Concise API, quick results
3D Support	Limited 3D via mpl_toolkits	Excellent 3D support
Web Integration	Not designed for web	Built for web, supports Dash
Style	Basic defaults, customizable	Modern, polished defaults
Best for	Publication figures, static reports	Interactive dashboards, web apps


Q10. What is the significance of hierarchical indexing in Pandas?
Hierarchical indexing (also called MultiIndex) in Pandas allows multiple index levels to exist on a single axis of a DataFrame or Series. This enables representation of higher-dimensional data in a lower-dimensional structure, and is particularly useful for panel data, time series with multiple instruments, or grouped data with multiple levels.
•	Efficient Data Representation: Store and query data with multiple grouping variables without losing structure.
•	Powerful Selection: Access data using partial indexing at any level of the hierarchy.
•	Pivot and Reshape: MultiIndex enables powerful unstack(), stack(), and pivot_table() operations.
import pandas as pd
arrays = [['Math','Math','Science','Science'],
          ['Exam1','Exam2','Exam1','Exam2']]
index = pd.MultiIndex.from_arrays(arrays, names=['Subject','Test'])
scores = pd.Series([88, 92, 75, 80], index=index)
print(scores['Math'])  # Access all Math scores
Output: Test
Exam1    88
Exam2    92
dtype: int64

Q11. What is the role of Seaborn's pairplot() function?
Seaborn's pairplot() function creates a grid of scatter plots showing pairwise relationships between all numerical variables in a dataset. Along the diagonal, it shows the distribution of each individual variable (as a histogram or KDE plot). This is extremely useful in exploratory data analysis (EDA) for quickly understanding relationships and correlations between multiple features.
•	Identify Correlations: Quickly spot linear or non-linear relationships between variables.
•	Detect Clusters: If hue parameter is used, colored clusters reveal class separability.
•	Find Outliers: Outliers appear as isolated points far from the main cluster.
•	Check Distributions: Diagonal plots show the marginal distribution of each feature.
import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset('iris')
sns.pairplot(iris, hue='species', diag_kind='kde')
plt.suptitle('Iris Dataset Pairplot', y=1.02)
plt.show()
This single function call produces a 4×4 grid of plots for the Iris dataset, revealing that petal_length and petal_width are highly discriminative between the three species.

Q12. What is handling missing data important in Pandas?
Missing data (represented as NaN in Pandas) is a common reality in real-world datasets. Failing to handle missing data correctly can lead to biased models, incorrect statistics, and runtime errors. Pandas provides comprehensive tools for detecting, filling, and dropping missing values.
Methods for Handling Missing Data:
Method	Description	Use Case
isnull() / isna()	Detect missing values (returns bool mask)	Finding where NaNs exist
fillna(value)	Fill NaN with specified value or strategy	Imputation with mean/median/mode
dropna()	Drop rows/columns with NaN	When missing data is small fraction
interpolate()	Fill using interpolation	Time series data
ffill() / bfill()	Forward/backward fill	Sequential or time data


Q13. What are the benefits of using Plotly for data visualization?
•	Interactivity Out of the Box: Hover tooltips, zoom, pan, and click events require zero extra code.
•	Web-Ready: Outputs HTML files embeddable in web pages, or used with Dash for full dashboards.
•	3D Visualizations: First-class support for 3D scatter, surface, and mesh plots.
•	Wide Chart Library: Over 40 chart types including sunburst, sankey, treemap, and geo maps.
•	Express API: plotly.express offers one-line chart creation for most common visualizations.
•	Subplots and Facets: Easy multi-panel layouts with make_subplots().
•	Animation Support: Create animated charts showing data evolution over time.

Q14. How does NumPy handle multidimensional arrays?
NumPy's core data structure is the ndarray (N-dimensional array), which generalizes to any number of dimensions. Each dimension is called an axis. NumPy provides attributes and methods to inspect and manipulate the shape, size, and structure of multidimensional arrays.
Attribute/Method	Description
arr.ndim	Number of dimensions
arr.shape	Tuple of sizes along each dimension
arr.size	Total number of elements
arr.reshape()	Change array shape (without copying data)
arr.transpose()	Reverse or permute axes
arr.flatten()	Collapse to 1D array

import numpy as np
arr = np.arange(24).reshape(2, 3, 4)  # 3D array: 2 blocks, 3 rows, 4 cols
print('Shape:', arr.shape)   # (2, 3, 4)
print('Dims:', arr.ndim)     # 3
print('Size:', arr.size)     # 24

Q15. What is the role of Bokeh in data visualization?
Bokeh is a Python interactive visualization library that targets modern web browsers for presentation. It is designed to produce elegant, concise construction of versatile graphics, and to extend this capability with high-performance interactivity over very large or streaming datasets.
•	Server-Side Rendering: Can handle very large datasets via BokehServer, streaming only what is needed.
•	Widgets: Sliders, dropdowns, buttons can be linked to plots for dynamic filtering.
•	Layouts: Easily combine multiple plots in rows, columns, or tab panels.
•	JavaScript Callbacks: Allows custom JavaScript logic for highly interactive behavior.
•	Comparison with Plotly: Bokeh offers more fine-grained control for complex dashboards; Plotly is simpler for quick interactive charts.

Q16. Explain the difference between apply() and map() in Pandas.
Feature	map()	apply()
Works on	Series only	Series and DataFrame
Function input	Element-wise (one value at a time)	Element-wise or axis-wise
Typical use	Simple element transformation	Complex operations on rows/columns
Returns	Series	Series or DataFrame
NaN handling	Passes NaN to function	Usually skips NaN

import pandas as pd
df = pd.DataFrame({'Name': ['alice', 'bob'], 'Score': [85, 90]})

# map(): transform Series element-wise
df['Name'] = df['Name'].map(str.title)

# apply(): apply function to each row (axis=1)
df['Grade'] = df['Score'].apply(lambda x: 'A' if x >= 90 else 'B')
print(df)
Output:    Name  Score Grade
0  Alice     85     B
1    Bob     90     A

Q17. What are some advanced features of NumPy?
•	Linear Algebra (np.linalg): Matrix multiplication, determinant, inverse, eigenvalues, SVD decomposition.
•	Random Module (np.random): Generate random arrays, shuffle, sample from distributions (normal, binomial, etc.).
•	Universal Functions (ufuncs): Fast element-wise operations that support broadcasting and output parameters.
•	Structured Arrays: Arrays with named fields, similar to database records.
•	Memory-mapped Files (np.memmap): Work with large arrays stored on disk without loading into RAM.
•	Masked Arrays (np.ma): Arrays with a mask to ignore invalid or missing data.
•	FFT (np.fft): Fast Fourier Transform for signal processing.

Q18. How does Pandas simplify time series analysis?
Pandas has been designed with time series data as a first-class citizen. It provides powerful tools for indexing, resampling, rolling calculations, and date offset arithmetic that make time series analysis far easier than with raw Python.
•	DatetimeIndex: A specialized index for datetime objects that enables powerful time-based selection.
•	pd.to_datetime(): Parse date strings in any format into datetime objects.
•	resample(): Group time series by any frequency (daily, weekly, monthly) and aggregate.
•	rolling(): Compute rolling/moving window statistics (rolling mean, rolling std).
•	shift(): Shift data forward or backward in time for lag calculations.
•	date_range(): Generate a sequence of dates at regular intervals.
import pandas as pd
dates = pd.date_range('2024-01-01', periods=6, freq='M')
sales = pd.Series([1200, 1500, 980, 1800, 2100, 1600], index=dates)
print(sales.resample('Q').sum())  # Quarterly totals
Output: 2024-03-31    3680
2024-06-30    5500
Freq: Q-DEC, dtype: int64

Q19. What is the role of a pivot table in Pandas?
A pivot table in Pandas is a data summarization tool that aggregates data by grouping values along one or more categorical variables and computing summary statistics. It is the Python equivalent of Excel's Pivot Table feature and is created using pd.pivot_table().
•	Summarize Data: Quickly compute totals, averages, counts across categories.
•	Multi-dimensional View: Group by multiple row and column variables simultaneously.
•	Flexible Aggregation: Support for any aggregation function (sum, mean, max, custom).
import pandas as pd
df = pd.DataFrame({'Region':['East','West','East','West','East'],
                   'Product':['A','A','B','B','A'],
                   'Sales':[100,200,150,250,120]})
pivot = pd.pivot_table(df, values='Sales', index='Region',
                       columns='Product', aggfunc='sum', fill_value=0)
print(pivot)
Output: Product    A    B
Region
East     220  150
West     200  250

Q20. Why is NumPy's array slicing faster than Python's list slicing?
NumPy array slicing is faster than Python list slicing for several fundamental reasons:
•	No-Copy View: NumPy slices return a view of the original array — no data is copied. Python list slicing creates a new list with copied elements.
•	Contiguous Memory: NumPy stores data in contiguous memory, so slicing is a simple pointer offset operation. Python list elements are scattered in memory.
•	C-Level Operations: NumPy slicing is implemented in C and operates directly on the memory buffer.
•	Data Type Consistency: Because NumPy arrays are homogeneous, the size of each element is known in advance, enabling direct offset calculations.
import numpy as np
arr = np.arange(1000000)
view = arr[100:900]   # No copy — just a new view pointer
view[0] = 999         # This modifies the original arr[100] too!
print(arr[100])       # 999

Q21. What are some common use cases for Seaborn?
•	Distribution Analysis: histplot(), kdeplot(), ecdfplot() for understanding data distributions.
•	Relationship Exploration: scatterplot(), regplot(), lmplot() for bivariate analysis.
•	Categorical Comparisons: boxplot(), violinplot(), barplot(), stripplot() for comparing groups.
•	Correlation Heatmaps: heatmap() for visualizing correlation matrices.
•	Pairwise Relationships: pairplot() for comprehensive EDA of all feature pairs.
•	Faceted Grids: FacetGrid for conditional plots split by categories.
•	Statistical Estimation: Automatic confidence interval display on most plots.

Q22. What are some advanced features of NumPy?
(Note: This extends Q17 with additional advanced NumPy capabilities.)
•	np.einsum(): Einstein summation notation — an extremely powerful and efficient way to express complex multi-dimensional operations (matrix products, traces, transposes) in a single expression.
•	Structured/Record Arrays: Arrays where each element is a record with named fields of different types, useful for CSV-like data at C speed.
•	np.vectorize(): Convert any Python function into a vectorized NumPy function automatically.
•	C Extensions Interface: NumPy arrays can be passed to C, C++, and Fortran code via ctypes or Cython for maximum performance.
•	np.lib.stride_tricks: Manipulate array strides directly to create sliding window views with zero copying.
import numpy as np
# einsum: matrix multiplication
A = np.random.rand(3, 4)
B = np.random.rand(4, 5)
C = np.einsum('ij,jk->ik', A, B)  # Equivalent to A @ B
print('Shape:', C.shape)  # (3, 5)


SECTION 2: Practical Questions

PQ1. Create a 2D NumPy array and calculate the sum of each row.
This program creates a 2D NumPy array (matrix), displays it, and then computes the sum of each row using np.sum() with axis=1.
import numpy as np

# Create a 4x5 2D array with values 1 to 20
arr_2d = np.arange(1, 21).reshape(4, 5)
print('2D Array (4 rows x 5 columns):')
print(arr_2d)
print()

# Sum of each row (axis=1 means across columns)
row_sums = np.sum(arr_2d, axis=1)
print('Sum of each row:', row_sums)

# Sum of each column (axis=0 means down rows)
col_sums = np.sum(arr_2d, axis=0)
print('Sum of each column:', col_sums)

# Total sum
print('Total sum of all elements:', np.sum(arr_2d))

# Additional statistics
print('Row means:', np.mean(arr_2d, axis=1))
print('Row max:', np.max(arr_2d, axis=1))
Output: 2D Array (4 rows x 5 columns):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum of each row: [ 15  40  65  90]
Sum of each column: [34 38 42 46 50]
Total sum of all elements: 210
Row means: [ 3.  8. 13. 18.]
Row max: [ 5 10 15 20]
Explanation: reshape(4,5) converts the 1D arange into a 4x5 matrix. axis=1 directs the sum operation across columns (per row). axis=0 sums down rows (per column).

PQ2. Write a Pandas script to find the mean of a specific column in a DataFrame.
import pandas as pd
import numpy as np

# Create a sample student DataFrame
data = {
    'Student': ['Alice','Bob','Charlie','Diana','Edward','Fiona'],
    'Math':    [88, 72, 95, 61, 84, 90],
    'Science': [75, 85, 92, 78, 65, 88],
    'English': [90, 68, 79, 83, 71, 94]
}
df = pd.DataFrame(data)
print('Student DataFrame:')
print(df)
print()

# Mean of a specific column
math_mean = df['Math'].mean()
print(f'Mean of Math scores: {math_mean:.2f}')

# Mean of all numeric columns
print('\nMean of all subjects:')
print(df[['Math','Science','English']].mean())

# Conditional mean: mean Math score for students scoring > 80 in Science
cond_mean = df[df['Science'] > 80]['Math'].mean()
print(f'\nMean Math score (Science>80): {cond_mean:.2f}')
Output: Mean of Math scores: 81.67

Mean of all subjects:
Math       81.67
Science    80.50
English    80.83

Mean Math score (Science>80): 85.67

PQ3. Create a scatter plot using Matplotlib.
import matplotlib.pyplot as plt
import numpy as np

# Generate synthetic data: study hours vs exam scores
np.random.seed(42)
study_hours = np.random.uniform(1, 10, 50)
exam_scores = 5 * study_hours + np.random.normal(0, 5, 50)  # Linear + noise
exam_scores = np.clip(exam_scores, 0, 100)

# Scatter plot
fig, ax = plt.subplots(figsize=(8, 5))
scatter = ax.scatter(study_hours, exam_scores,
                     c=exam_scores, cmap='viridis',
                     s=80, alpha=0.7, edgecolors='black', linewidths=0.5)

# Add trend line
z = np.polyfit(study_hours, exam_scores, 1)
p = np.poly1d(z)
x_line = np.linspace(1, 10, 100)
ax.plot(x_line, p(x_line), 'r--', linewidth=2, label='Trend Line')

# Labels and formatting
ax.set_xlabel('Study Hours', fontsize=12)
ax.set_ylabel('Exam Score', fontsize=12)
ax.set_title('Study Hours vs Exam Score', fontsize=14, fontweight='bold')
plt.colorbar(scatter, ax=ax, label='Score Intensity')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('scatter_plot.png', dpi=150)
plt.show()
Explanation: np.random.seed(42) ensures reproducibility. The color (c=exam_scores, cmap='viridis') maps score to a color gradient. polyfit() computes a linear trend line. savefig() saves the plot to disk.

PQ4. Calculate the correlation matrix using Seaborn and visualize it with a heatmap.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Create a synthetic dataset
np.random.seed(10)
n = 100
df = pd.DataFrame({
    'Temperature':  np.random.normal(25, 5, n),
    'Humidity':     np.random.normal(60, 10, n),
    'Wind_Speed':   np.random.normal(15, 4, n),
    'Rainfall':     np.random.normal(5, 2, n),
    'Solar_Energy': np.random.normal(200, 30, n)
})

# Add artificial correlation
df['Rainfall'] = df['Humidity'] * 0.05 + np.random.normal(0, 1, n)

# Compute correlation matrix
corr_matrix = df.corr()
print('Correlation Matrix:')
print(corr_matrix.round(2))

# Seaborn heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix,
            annot=True,
            fmt='.2f',
            cmap='RdYlGn',
            center=0,
            square=True,
            linewidths=0.5,
            cbar_kws={'shrink': 0.8})
plt.title('Weather Variable Correlation Heatmap', fontsize=14, pad=15)
plt.tight_layout()
plt.savefig('heatmap.png', dpi=150)
plt.show()
Explanation: df.corr() computes the Pearson correlation between all pairs of numeric columns (values range from -1 to +1). annot=True writes coefficients in cells. cmap='RdYlGn' uses red for negative, green for positive correlations. center=0 ensures zero correlation maps to yellow/white.

PQ5. Generate a bar plot using Plotly.
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

# Monthly sales data for three products
df = pd.DataFrame({
    'Month': ['Jan','Feb','Mar','Apr','May','Jun'] * 3,
    'Product': ['Laptop']*6 + ['Phone']*6 + ['Tablet']*6,
    'Sales': [120,135,98,150,175,160,
              200,180,220,195,240,210,
              80, 90, 75, 110, 95, 100]
})

# Grouped bar chart using plotly.express
fig = px.bar(df, x='Month', y='Sales', color='Product',
             barmode='group',
             title='Monthly Sales by Product',
             labels={'Sales': 'Units Sold', 'Month': 'Month'},
             color_discrete_sequence=px.colors.qualitative.Set2)

fig.update_layout(
    xaxis_title='Month',
    yaxis_title='Units Sold',
    legend_title='Product',
    bargap=0.15,
    template='plotly_white'
)

fig.write_html('sales_bar_chart.html')  # Save as interactive HTML
fig.show()
Explanation: px.bar() is from plotly.express, the high-level Plotly API. barmode='group' places bars side by side. The output HTML file is fully interactive — users can hover for exact values, click legend to hide/show products, and zoom. template='plotly_white' provides a clean white background.

PQ6. Create a DataFrame and add a new column based on an existing column.
import pandas as pd
import numpy as np

# Employee DataFrame
df = pd.DataFrame({
    'Employee': ['Alice','Bob','Charlie','Diana','Edward'],
    'Salary':   [55000, 72000, 48000, 89000, 61000],
    'Years':    [3, 7, 2, 10, 5],
    'Department': ['HR','IT','Finance','IT','HR']
})

# Add column 1: Annual Bonus (10% of salary)
df['Bonus'] = df['Salary'] * 0.10

# Add column 2: Tax bracket based on salary
def tax_bracket(salary):
    if salary < 50000: return 'Low (10%)'
    elif salary < 75000: return 'Medium (20%)'
    else: return 'High (30%)'

df['Tax_Bracket'] = df['Salary'].apply(tax_bracket)

# Add column 3: Experience level
df['Level'] = pd.cut(df['Years'],
                     bins=[0, 3, 7, float('inf')],
                     labels=['Junior','Mid','Senior'])

# Add column 4: Total compensation
df['Total_Comp'] = df['Salary'] + df['Bonus']

print(df.to_string(index=False))
Output: Employee  Salary  Years Department   Bonus Tax_Bracket   Level  Total_Comp
   Alice   55000      3         HR  5500.0 Medium(20%)   Junior     60500.0
     Bob   72000      7         IT  7200.0 Medium(20%)      Mid     79200.0
 Charlie   48000      2    Finance  4800.0   Low(10%)   Junior     52800.0
   Diana   89000     10         IT  8900.0   High(30%)   Senior     97900.0
  Edward   61000      5         HR  6100.0 Medium(20%)      Mid     67100.0

PQ7. Write a program to perform element-wise multiplication of two NumPy arrays.
import numpy as np

print('=== Element-wise Multiplication Demo ===\n')

# 1D arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print('Array a:', a)
print('Array b:', b)
print('a * b (element-wise):', a * b)
print('np.multiply(a, b):', np.multiply(a, b))

# 2D array element-wise multiplication
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
print('\n2D Element-wise (A * B):')
print(A * B)

# Broadcasting: multiply 2D array by 1D array
C = np.array([1, 2, 3])
print('\nBroadcast (A * C):')
print(A * C)

# Matrix multiplication (NOT element-wise — for comparison)
print('\nMatrix multiply (A @ B.T) shape:', (A @ B.T).shape)
Output: Array a: [1 2 3 4 5]
Array b: [10 20 30 40 50]
a * b (element-wise): [ 10  40  90 160 250]

2D Element-wise (A * B):
[[ 7 16 27]
 [40 55 72]]

Broadcast (A * C):
[[ 1  4  9]
 [ 4 10 18]]

PQ8. Create a line plot with multiple lines using Matplotlib.
import matplotlib.pyplot as plt
import numpy as np

# Data: Monthly performance of three departments
months = np.arange(1, 13)
month_labels = ['Jan','Feb','Mar','Apr','May','Jun',
                'Jul','Aug','Sep','Oct','Nov','Dec']

np.random.seed(5)
dept_A = [52, 58, 61, 70, 75, 80, 78, 85, 82, 90, 94, 99]
dept_B = [40, 45, 50, 48, 55, 60, 65, 63, 70, 72, 68, 75]
dept_C = [70, 65, 68, 72, 69, 74, 80, 85, 88, 83, 90, 95]

fig, ax = plt.subplots(figsize=(11, 5))

ax.plot(month_labels, dept_A, marker='o', linewidth=2,
        color='#2196F3', label='Department A', markersize=6)
ax.plot(month_labels, dept_B, marker='s', linewidth=2,
        color='#F44336', label='Department B', markersize=6)
ax.plot(month_labels, dept_C, marker='^', linewidth=2,
        color='#4CAF50', label='Department C', markersize=6)

# Shade the area below line A
ax.fill_between(month_labels, dept_A, alpha=0.1, color='#2196F3')

ax.set_title('Monthly Performance Score by Department (2024)',
             fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Month', fontsize=12)
ax.set_ylabel('Performance Score', fontsize=12)
ax.legend(fontsize=11, loc='upper left')
ax.grid(True, linestyle='--', alpha=0.5)
ax.set_ylim(30, 110)
plt.tight_layout()
plt.savefig('multi_line_plot.png', dpi=150)
plt.show()
Explanation: Each ax.plot() call adds a line to the same axes. marker, color, and linewidth control appearance. fill_between() shades the region under a line. grid() with linestyle='--' and alpha=0.5 adds subtle gridlines. tight_layout() prevents label clipping.

PQ9. Generate a Pandas DataFrame and filter rows where a column value is greater than a threshold.
import pandas as pd
import numpy as np

# Product inventory DataFrame
np.random.seed(7)
df = pd.DataFrame({
    'Product_ID':  [f'P{i:03d}' for i in range(1, 16)],
    'Product_Name':['Widget A','Widget B','Gadget X','Gadget Y','Tool Z',
                    'Device P','Device Q','Module R','Module S','Part T',
                    'Part U','Item V','Item W','Unit X','Unit Y'],
    'Price':       [25,85,120,45,300,55,210,90,35,180,70,250,40,65,315],
    'Stock':       [150,80,30,200,15,120,45,90,300,25,175,10,400,60,8],
    'Rating':      [4.2,3.8,4.9,4.1,4.7,3.5,4.6,4.3,3.9,4.8,4.0,4.5,3.7,4.4,4.6]
})

print('Full DataFrame:')
print(df.head())
print(f'\nTotal products: {len(df)}')

# Filter 1: Price > 100
expensive = df[df['Price'] > 100]
print(f'\nProducts with Price > $100 ({len(expensive)} items):')
print(expensive[['Product_Name','Price','Rating']])

# Filter 2: Rating > 4.5 AND Stock < 50
premium_low_stock = df[(df['Rating'] > 4.5) & (df['Stock'] < 50)]
print(f'\nHigh-rated low-stock (Rating>4.5 & Stock<50):')
print(premium_low_stock[['Product_Name','Price','Stock','Rating']])

# Filter 3: Using query() method
affordable_good = df.query('Price < 100 and Rating >= 4.0')
print(f'\nAffordable and good (Price<100, Rating>=4.0):')
print(affordable_good[['Product_Name','Price','Rating']])
Output: Products with Price > $100 (5 items):
     Product_Name  Price  Rating
2     Gadget X     120     4.9
4       Tool Z     300     4.7
6     Device Q     210     4.6
9       Part T     180     4.8
11      Item V     250     4.5

PQ10. Create a histogram using Seaborn to visualize a distribution.
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Generate synthetic exam scores for three classes
np.random.seed(42)
class_A = np.random.normal(loc=72, scale=10, size=120)  # Mean 72
class_B = np.random.normal(loc=65, scale=15, size=120)  # More spread
class_C = np.random.normal(loc=80, scale=8,  size=120)  # High performers

df = pd.DataFrame({
    'Score': np.concatenate([class_A, class_B, class_C]),
    'Class': ['A']*120 + ['B']*120 + ['C']*120
})
df['Score'] = df['Score'].clip(0, 100)

# Multi-panel histograms using FacetGrid
fig, axes = plt.subplots(1, 3, figsize=(14, 5), sharey=True)
colors = ['#3498DB', '#E74C3C', '#2ECC71']
labels = ['Class A', 'Class B', 'Class C']

for ax, cls, color, lbl in zip(axes, ['A','B','C'], colors, labels):
    subset = df[df['Class'] == cls]['Score']
    sns.histplot(subset, bins=20, kde=True, color=color,
                 alpha=0.7, ax=ax)
    ax.axvline(subset.mean(), color='black', linestyle='--', linewidth=1.5)
    ax.set_title(f'{lbl}\nMean: {subset.mean():.1f}', fontsize=12)
    ax.set_xlabel('Exam Score')
    ax.set_ylabel('Count')

fig.suptitle('Exam Score Distribution by Class', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.savefig('histogram_seaborn.png', dpi=150)
plt.show()
Explanation: sns.histplot() with kde=True overlays a smooth Kernel Density Estimation curve over the histogram bars. axvline() draws a vertical dashed line at the mean. sharey=True keeps the y-axis consistent across subplots for easy visual comparison.

PQ11. Perform matrix multiplication using NumPy.
import numpy as np

print('=== Matrix Multiplication with NumPy ===\n')

# Define matrices
A = np.array([[1, 2, 3],
              [4, 5, 6]])
# Shape: (2, 3)

B = np.array([[7,  8],
              [9,  10],
              [11, 12]])
# Shape: (3, 2)

print(f'Matrix A (shape {A.shape}):\n{A}\n')
print(f'Matrix B (shape {B.shape}):\n{B}\n')

# Method 1: @ operator (recommended)
C1 = A @ B
print(f'A @ B (shape {C1.shape}):\n{C1}\n')

# Method 2: np.matmul()
C2 = np.matmul(A, B)
print(f'np.matmul(A,B):\n{C2}\n')

# Method 3: np.dot()
C3 = np.dot(A, B)
print(f'np.dot(A,B):\n{C3}\n')

# Square matrix inverse and solve linear system
M = np.array([[2.0, 1.0], [1.0, 3.0]])
print(f'Matrix M:\n{M}')
print(f'Inverse of M:\n{np.linalg.inv(M).round(3)}')
print(f'Determinant: {np.linalg.det(M):.2f}')

# Solve: Mx = b
b = np.array([5.0, 10.0])
x = np.linalg.solve(M, b)
print(f'Solution to Mx=b: {x}')
Output: A @ B (shape (2, 2)):
[[ 58  64]
 [139 154]]

Inverse of M:
[[ 0.6  -0.2]
 [-0.2   0.4]]
Determinant: 5.00
Solution to Mx=b: [1. 3.]

PQ12. Use Pandas to load a CSV file and display its first 5 rows.
import pandas as pd
import numpy as np
import os

# --- Part A: Create and save a sample CSV (for demonstration) ---
sample_data = pd.DataFrame({
    'StudentID': range(1001, 1021),
    'Name': ['Alice','Bob','Charlie','Diana','Edward',
             'Fiona','George','Hannah','Ivan','Julia',
             'Karl','Lisa','Mike','Nina','Oscar',
             'Paula','Quinn','Rachel','Sam','Tina'],
    'Age': np.random.randint(18, 25, 20),
    'GPA': np.round(np.random.uniform(2.5, 4.0, 20), 2),
    'Major': np.random.choice(['CS','Math','Physics','Economics'], 20),
    'Scholarship': np.random.choice([True, False], 20)
})
sample_data.to_csv('students.csv', index=False)
print('CSV file created: students.csv')

# --- Part B: Load and explore the CSV ---
df = pd.read_csv('students.csv')

print(f'\nDataset Shape: {df.shape} ({df.shape[0]} rows, {df.shape[1]} columns)')
print(f'Column Names: {list(df.columns)}')

print('\n--- First 5 Rows ---')
print(df.head(5))

print('\n--- Dataset Info ---')
print(df.dtypes)

print('\n--- Basic Statistics ---')
print(df.describe().round(2))

print('\n--- Missing Values ---')
print(df.isnull().sum())
Output: CSV file created: students.csv
Dataset Shape: (20, 6) (20 rows, 6 columns)

--- First 5 Rows ---
   StudentID     Name  Age   GPA   Major  Scholarship
0       1001    Alice   21  3.42      CS         True
1       1002      Bob   19  2.87    Math        False
2       1003  Charlie   22  3.71  Physics         True
3       1004    Diana   20  3.15      CS        False
4       1005   Edward   23  2.95  Economics      True

PQ13. Create a 3D scatter plot using Plotly.
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
import pandas as pd

# Generate 3D data: simulated housing data
np.random.seed(42)
n = 200
area    = np.random.uniform(500, 3000, n)   # Square feet
rooms   = np.random.randint(1, 7, n)        # Number of rooms
age     = np.random.uniform(1, 50, n)       # Age of house (years)
price   = (area * 150 + rooms * 20000 - age * 500
           + np.random.normal(0, 15000, n)) # Price in $
price   = np.maximum(price, 50000)

neighborhood = np.random.choice(['Downtown','Suburbs','Rural'], n,
                                 p=[0.3, 0.5, 0.2])

df = pd.DataFrame({'Area_sqft': area.round(0),
                   'Rooms': rooms,
                   'Age_years': age.round(1),
                   'Price_USD': price.round(0),
                   'Neighborhood': neighborhood})

# 3D scatter plot
fig = px.scatter_3d(df,
    x='Area_sqft',
    y='Rooms',
    z='Price_USD',
    color='Neighborhood',
    size='Age_years',
    hover_data=['Age_years', 'Price_USD'],
    title='3D Housing Data: Area vs Rooms vs Price',
    labels={'Area_sqft':'Area (sq ft)',
            'Price_USD':'Price ($)',
            'Rooms':'Number of Rooms'},
    color_discrete_sequence=px.colors.qualitative.Bold
)

fig.update_traces(marker=dict(opacity=0.7, line=dict(width=0.5, color='DarkSlateGrey')))
fig.update_layout(
    scene=dict(
        xaxis_title='Area (sq ft)',
        yaxis_title='Number of Rooms',
        zaxis_title='Price ($)'
    ),
    margin=dict(l=0, r=0, b=0, t=40),
    template='plotly_white'
)

fig.write_html('3d_scatter.html')
fig.show()
Explanation: px.scatter_3d() maps three numeric variables to X, Y, Z axes. The color='Neighborhood' argument automatically assigns distinct colors per category. size='Age_years' makes older houses appear as larger points. The output HTML allows full 3D rotation, zoom, and hover inspection directly in any web browser.

